/**
 * Phân loại chủ đề (spec P1-V). Dùng nhiều tín hiệu: chủ đề nguồn
 * (semanticCategory krdict, topic seed cũ), từ khóa trong meaningVi/term/
 * example/tags — KHÔNG chỉ dựa headword. Tối đa 3 chủ đề, nhận khi
 * confidence >= 0.6; không đủ → unclassified.
 */
import type { VocabularyItem } from "../../types";
import {
  CURRICULUM_TOPICS,
  type CurriculumTopicId,
} from "../../config/curriculum/topics";

export interface TopicResult {
  topicIds: CurriculumTopicId[];
  topicStatus: "source" | "rule" | "unclassified";
  topicConfidence: number;
}

/** Chủ đề nguồn (legacy topic / semanticCategory đã Việt hóa) → taxonomy. */
const SOURCE_TOPIC_MAP: Record<string, CurriculumTopicId> = {
  "Chào hỏi": "greetings",
  "Gia đình": "family",
  "Con người": "people",
  "Số đếm": "numbers",
  "Thời gian": "time",
  "Đời sống": "daily-life",
  "Đời sống hằng ngày": "daily-life",
  "Đời sống xã hội": "society",
  "Ẩm thực": "food",
  "Ăn uống": "food",
  "Nhà ở": "housing",
  "Trường học": "school",
  "Giáo dục": "school",
  "Công việc": "work",
  "Kinh tế": "work",
  "Mua sắm": "shopping",
  "Giao thông": "transport",
  "Du lịch": "travel",
  "Sức khỏe": "health",
  "Cảm xúc": "feelings",
  "Thiên nhiên": "nature",
  "Tự nhiên": "nature",
  "Động – Thực vật": "nature",
  "Thời tiết": "weather",
  "Xã hội": "society",
  "Chính trị – Hành chính": "society",
  "Tôn giáo": "culture",
  "Văn hóa": "culture",
  "Thể thao": "culture",
  "Trang phục": "shopping",
  "Giao tiếp": "communication",
  "Khoa học": "science",
  "Khoa học – Kỹ thuật": "science",
  "Khái niệm": "other",
  "Công nghệ": "technology",
  "Điện tử": "electronics",
  "Điện – Điện tử": "electronics",
  "Viễn thông": "telecommunications",
  Mạng: "telecommunications",
  "Phỏng vấn": "job-interview",
};

/** Từ khóa quy tắc — so trong meaningVi (vi) và term/tags (en/zh/ja/ko). */
const TOPIC_KEYWORDS: Partial<
  Record<CurriculumTopicId, { vi: string[]; xx: string[] }>
> = {
  greetings: {
    vi: ["xin chào", "tạm biệt", "chào hỏi", "cảm ơn", "xin lỗi"],
    xx: [
      "hello",
      "goodbye",
      "thanks",
      "你好",
      "再见",
      "谢谢",
      "こんにちは",
      "ありがとう",
      "안녕",
      "감사",
    ],
  },
  family: {
    vi: [
      "bố",
      "mẹ",
      "anh trai",
      "chị gái",
      "em trai",
      "em gái",
      "ông ",
      "bà ",
      "con trai",
      "con gái",
      "gia đình",
      "vợ",
      "chồng",
      "cháu",
    ],
    xx: [
      "father",
      "mother",
      "family",
      "爸",
      "妈",
      "家族",
      "家人",
      "가족",
      "부모",
    ],
  },
  numbers: {
    vi: [
      "số ",
      "một",
      "hai",
      "ba ",
      "bốn",
      "năm ",
      "sáu",
      "bảy",
      "tám",
      "chín",
      "mười",
      "trăm",
      "nghìn",
      "đếm",
    ],
    xx: ["number", "count"],
  },
  time: {
    vi: [
      "giờ",
      "phút",
      "giây",
      "hôm nay",
      "ngày mai",
      "hôm qua",
      "tuần",
      "tháng",
      "mùa ",
      "buổi sáng",
      "buổi tối",
      "thời gian",
      "năm nay",
    ],
    xx: ["time", "hour", "minute", "week", "month", "時間", "시간"],
  },
  food: {
    vi: [
      "ăn",
      "uống",
      "đồ ăn",
      "món ăn",
      "nhà hàng",
      "bữa",
      "cơm",
      "thịt",
      "rau",
      "trái cây",
      "nấu",
      "bánh",
      "nước ",
      "trà",
      "cà phê",
      "rượu",
    ],
    xx: [
      "eat",
      "drink",
      "food",
      "meal",
      "restaurant",
      "吃",
      "喝",
      "饭",
      "菜",
      "食べ",
      "飲",
      "料理",
      "먹다",
      "마시",
      "음식",
      "식사",
    ],
  },
  housing: {
    vi: [
      "nhà",
      "phòng",
      "cửa",
      "bàn",
      "ghế",
      "giường",
      "bếp",
      "căn hộ",
      "tường",
      "mái",
    ],
    xx: ["house", "room", "apartment", "家", "房", "部屋", "집", "방"],
  },
  school: {
    vi: [
      "học",
      "trường",
      "lớp",
      "giáo viên",
      "học sinh",
      "sinh viên",
      "bài tập",
      "thi ",
      "sách giáo khoa",
      "đại học",
    ],
    xx: [
      "school",
      "study",
      "student",
      "teacher",
      "学校",
      "学生",
      "学ぶ",
      "학교",
      "학생",
      "공부",
    ],
  },
  work: {
    vi: [
      "làm việc",
      "công việc",
      "công ty",
      "văn phòng",
      "nghề",
      "lương",
      "họp",
      "kinh doanh",
      "khách hàng",
      "nhân viên",
      "giám đốc",
      "tiền",
    ],
    xx: [
      "work",
      "job",
      "office",
      "company",
      "business",
      "工作",
      "公司",
      "仕事",
      "会社",
      "일하다",
      "회사",
      "직장",
    ],
  },
  shopping: {
    vi: [
      "mua",
      "bán",
      "giá",
      "tiền",
      "cửa hàng",
      "chợ",
      "siêu thị",
      "đắt",
      "rẻ",
      "quần áo",
      "áo",
      "quần",
      "giày",
    ],
    xx: [
      "buy",
      "sell",
      "shop",
      "price",
      "买",
      "卖",
      "商店",
      "買う",
      "店",
      "사다",
      "팔다",
      "가게",
    ],
  },
  transport: {
    vi: [
      "xe ",
      "tàu",
      "máy bay",
      "đường",
      "đi lại",
      "ga ",
      "bến",
      "lái",
      "giao thông",
      "xe buýt",
      "tàu điện",
    ],
    xx: [
      "car",
      "train",
      "bus",
      "road",
      "车",
      "路",
      "電車",
      "駅",
      "차",
      "기차",
      "버스",
    ],
  },
  travel: {
    vi: [
      "du lịch",
      "khách sạn",
      "hộ chiếu",
      "chuyến đi",
      "tham quan",
      "hành lý",
      "vé ",
    ],
    xx: ["travel", "hotel", "trip", "旅行", "ホテル", "여행", "호텔"],
  },
  health: {
    vi: [
      "bệnh",
      "đau",
      "thuốc",
      "bác sĩ",
      "bệnh viện",
      "sức khỏe",
      "khám",
      "cơ thể",
      "mắt",
      "tay",
      "chân",
      "đầu ",
      "tim",
      "máu",
    ],
    xx: [
      "sick",
      "doctor",
      "hospital",
      "medicine",
      "病",
      "医",
      "药",
      "病院",
      "薬",
      "아프다",
      "병원",
      "약",
      "의사",
    ],
  },
  feelings: {
    vi: [
      "vui",
      "buồn",
      "giận",
      "sợ",
      "yêu",
      "ghét",
      "hạnh phúc",
      "lo lắng",
      "ngạc nhiên",
      "cảm xúc",
      "thích",
    ],
    xx: [
      "happy",
      "sad",
      "angry",
      "love",
      "fear",
      "高兴",
      "爱",
      "嬉しい",
      "悲しい",
      "기쁘다",
      "슬프다",
      "사랑",
    ],
  },
  nature: {
    vi: [
      "cây",
      "hoa",
      "núi",
      "sông",
      "biển",
      "rừng",
      "động vật",
      "chim",
      "cá ",
      "chó",
      "mèo",
      "thiên nhiên",
      "đất",
      "đá ",
    ],
    xx: [
      "tree",
      "mountain",
      "river",
      "sea",
      "animal",
      "山",
      "水",
      "花",
      "海",
      "나무",
      "산",
      "바다",
      "꽃",
    ],
  },
  weather: {
    vi: [
      "mưa",
      "nắng",
      "gió",
      "tuyết",
      "mây",
      "thời tiết",
      "nóng",
      "lạnh",
      "bão",
      "nhiệt độ",
    ],
    xx: [
      "rain",
      "sunny",
      "wind",
      "snow",
      "weather",
      "雨",
      "雪",
      "风",
      "天気",
      "비가",
      "날씨",
      "눈이",
    ],
  },
  society: {
    vi: [
      "xã hội",
      "chính phủ",
      "luật",
      "quốc gia",
      "dân",
      "thành phố",
      "chiến tranh",
      "hòa bình",
      "bầu cử",
      "quyền",
    ],
    xx: [
      "society",
      "government",
      "law",
      "nation",
      "社会",
      "国家",
      "法律",
      "사회",
      "국가",
      "법",
    ],
  },
  culture: {
    vi: [
      "văn hóa",
      "âm nhạc",
      "phim",
      "nghệ thuật",
      "lễ hội",
      "tôn giáo",
      "truyền thống",
      "thể thao",
      "bóng đá",
      "hát",
      "vẽ",
    ],
    xx: [
      "culture",
      "music",
      "movie",
      "art",
      "文化",
      "音乐",
      "映画",
      "文化",
      "문화",
      "음악",
      "영화",
    ],
  },
  communication: {
    vi: [
      "nói",
      "nghe",
      "đọc",
      "viết",
      "hỏi",
      "trả lời",
      "ngôn ngữ",
      "câu",
      "từ ngữ",
      "thư",
      "gọi điện",
      "trò chuyện",
    ],
    xx: [
      "speak",
      "listen",
      "read",
      "write",
      "language",
      "说",
      "话",
      "話す",
      "言葉",
      "말하다",
      "언어",
      "듣다",
    ],
  },
  science: {
    vi: [
      "khoa học",
      "toán",
      "vật lý",
      "hóa học",
      "thí nghiệm",
      "nghiên cứu",
      "sinh học",
    ],
    xx: [
      "science",
      "math",
      "physics",
      "chemistry",
      "科学",
      "数学",
      "科学",
      "과학",
      "수학",
    ],
  },
  technology: {
    vi: [
      "máy tính",
      "phần mềm",
      "internet",
      "điện thoại",
      "công nghệ",
      "dữ liệu",
      "lập trình",
      "trang web",
      "ứng dụng",
    ],
    xx: [
      "computer",
      "software",
      "internet",
      "phone",
      "电脑",
      "手机",
      "コンピュータ",
      "컴퓨터",
      "인터넷",
    ],
  },
  electronics: {
    vi: [
      "điện áp",
      "dòng điện",
      "điện trở",
      "tụ điện",
      "mạch",
      "linh kiện",
      "bán dẫn",
      "điện tử",
      "cảm biến",
      "vi mạch",
    ],
    xx: [
      "voltage",
      "current",
      "resistor",
      "capacitor",
      "circuit",
      "电压",
      "电流",
      "电路",
      "電圧",
      "回路",
      "전압",
      "회로",
    ],
  },
  telecommunications: {
    vi: [
      "tín hiệu",
      "tần số",
      "băng thông",
      "anten",
      "mạng",
      "viễn thông",
      "sóng",
      "truyền dẫn",
      "kênh",
    ],
    xx: [
      "signal",
      "frequency",
      "bandwidth",
      "antenna",
      "network",
      "信号",
      "频率",
      "信号",
      "周波数",
      "신호",
      "주파수",
    ],
  },
};

const clean = (s: string) => ` ${s.toLowerCase()} `;

/** Phân loại một mục. Pure. */
export function classifyTopics(item: VocabularyItem): TopicResult {
  // 1) Chủ đề nguồn đáng tin (semanticCategory/seed) → status "source".
  const src = SOURCE_TOPIC_MAP[item.topic];
  if (src && src !== "other") {
    return { topicIds: [src], topicStatus: "source", topicConfidence: 0.9 };
  }

  // 2) Quy tắc từ khóa trên nhiều tín hiệu.
  const viText = clean(
    `${item.meaningVi} ${item.exampleVi ?? ""} ${item.explanationVi ?? ""}`,
  );
  const xxText = clean(
    `${item.term} ${item.example ?? ""} ${(item.tags ?? []).join(" ")}`,
  );
  const scores = new Map<CurriculumTopicId, number>();
  for (const id of CURRICULUM_TOPICS) {
    const kw = TOPIC_KEYWORDS[id];
    if (!kw) continue;
    let score = 0;
    for (const k of kw.vi) if (viText.includes(k.toLowerCase())) score += 0.4;
    for (const k of kw.xx) if (xxText.includes(k.toLowerCase())) score += 0.35;
    if (score > 0) scores.set(id, Math.min(score, 1));
  }
  const ranked = [...scores.entries()]
    .filter(([, s]) => s >= 0.6 - 1e-9)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 3);
  if (ranked.length > 0) {
    return {
      topicIds: ranked.map(([id]) => id),
      topicStatus: "rule",
      topicConfidence: ranked[0][1],
    };
  }
  return { topicIds: [], topicStatus: "unclassified", topicConfidence: 0 };
}
